config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :videos, only: [ :index, :show ]
  resource :session
  resources :passwords, param: :token
  resources :articles, only: [ :index, :show ]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  namespace :admin do
    resources :videos
    resources :articles do
      member do
        patch :submit
        patch :approve
        patch :reject
      end
    end
    root "articles#index"
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  root "articles#index"
end

app/models/article.rb
class Article < ApplicationRecord
  has_one :content, as: :contentable, dependent: :destroy

  accepts_nested_attributes_for :content

  delegate :title, to: :content
  # delegate :comments, to: :content

  has_one_attached :cover_image

  enum :status, [ :draft, :waiting_for_review, :published ]
end

app/controllers/admin/articles_controller.rb
module Admin
  class Admin::ArticlesController < ApplicationController
    before_action :set_admin_article, only: %i[ show edit update destroy submit approve reject ]

    # GET /admin/articles or /admin/articles.json
    def index
      @articles = Article.all
      # @content = Content.al
    end

    def submit
      if @article.update(admin_article_params.merge(status: waiting_for_approve))
        redirect_to [ :admin, @article ], notice: "Article was successfully updated.", status: :see_other
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end

    def approve
      if @article.update(admin_article_params.merge(status: published))
        redirect_to [ :admin, @article ], notice: "Article was successfully updated.", status: :see_other
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end

    def reject
      if @article.update(admin_article_params.merge(status: draft))
        redirect_to [ :admin, @article ], notice: "Article was successfully updated.", status: :see_other
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
    # GET /admin/articles/1 or /admin/articles/1.json
    def show
    end

    # GET /admin/articles/new
    def new
      @article = Article.new(content: Content.new)
    end

    # GET /admin/articles/1/edit
    def edit
    end

    # POST /admin/articles or /admin/articles.json
    def create
      @article = Article.new(admin_article_params)
      if params[:commit_type] == "draft"
        @article.status = 0
      else
        @article.status = 1
      end

      respond_to do |format|
        if @article.save
          format.html { redirect_to [ :admin, @article ], notice: "Article was successfully created." }
          format.json { render :show, status: :created, location: @article }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @article.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /admin/articles/1 or /admin/articles/1.json
    def update
      respond_to do |format|
        @article.status = params[:status]
        if @article.update(admin_article_params)
          format.html { redirect_to [ :admin, @article ], notice: "Article was successfully updated.", status: :see_other }
          format.json { render :show, status: :ok, location: @article }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @article.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /admin/articles/1 or /admin/articles/1.json
    def destroy
      @article.destroy!

      respond_to do |format|
        format.html { redirect_to admin_articles_path, notice: "Article was successfully destroyed.", status: :see_other }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_admin_article
        @article = Article.find(params.expect(:id))
      end

      # Only allow a list of trusted parameters through.
      def admin_article_params
        params.expect(article: [ :title, :description, :cover_image, :status, content_attributes: [ :title ] ])
      end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show ]

  # GET /articles or /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  # def create
  #   @article = Article.new(article_params)

  #   respond_to do |format|
  #     if @article.save
  #       format.html { redirect_to @article, notice: "Article was successfully created." }
  #       format.json { render :show, status: :created, location: @article }
  #     else
  #       format.html { render :new, status: :unprocessable_entity }
  #       format.json { render json: @article.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # # PATCH/PUT /articles/1 or /articles/1.json
  # def update
  #   respond_to do |format|
  #     if @article.update(article_params)
  #       format.html { redirect_to @article, notice: "Article was successfully updated.", status: :see_other }
  #       format.json { render :show, status: :ok, location: @article }
  #     else
  #       format.html { render :edit, status: :unprocessable_entity }
  #       format.json { render json: @article.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # # DELETE /articles/1 or /articles/1.json
  # def destroy
  #   @article.destroy!

  #   respond_to do |format|
  #     format.html { redirect_to articles_path, notice: "Article was successfully destroyed.", status: :see_other }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.expect(article: [ :title, :description ])
    end
end

app/helpers/admin/articles_helper.rb
module Admin::ArticlesHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/admin/articles/_article.html.erb
 <%= link_to [ :admin, article ] do %>
 <div id="<%= dom_id article %>" class="border-1 border-gray-200 rounded-xl p-4 shadow-md hover:scale-95 cursor-pointer bg-white">
     <p>
         <% if article.cover_image.attached? %>
         <%= image_tag article.cover_image %>
         <% else %>
         No cover image available.
         <% end %>
     </p>
     <p>
         <%= article.title %>
     </p>

     <p>
         <strong>Description:</strong>
         <%= article.description %>
     </p>
     <p>
         <strong>Status:</strong>
         <%= article.status %>
     </p>
 </div>
 <% end %>

 <div>
    <h1>Comment</h1>
    <%
=begin%>
 <%= render article.comments %> 
<%
=end%>
 </div>

app/views/admin/articles/_form.html.erb
<% if article.persisted? %>
 <% submitURL = submit_admin_article_path(article) %>
 <% approveURL = approve_admin_article_path(article) %>
 <% rejectURL = reject_admin_article_path(article) %>
<% else %>
  <% submitURL = new_admin_article_path(article)%>
  <% approveURL = new_admin_article_path(article)%>
  <% rejectURL = new_admin_article_path(article)%>
<% end %>

<%= form_with(model: [ :admin, article ], data: { controller: "hello", "hello-submit-url-value": submitURL, "hello-approve-url-value": approveURL, "hello-approve-url-value": rejectURL, "hello-target": "form" }) do |form| %>
  <% if article.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="flex flex-col gap-6 justify-center">
    

  <%= form.fields_for :content do |content_form| %>
  <div>
    <%= content_form.label :title, class: 'block'  %>
    <%= content_form.text_field :title, class: 'border-1 w-full input w-full p-4' %>
  </div>

  <% end %>

    <fieldset class="fieldset">
      <legend class="fieldset-legend">Description</legend>
      <%= form.text_area :description, class: "input h-100 w-full p-4", placeholder: "Highlight the key points in a few sentences"  %>
    </fieldset>
    <fieldset class="fieldset">
      <%= form.label :cover_image, class: "block mb-2 font-semibold" %>
      <%= form.file_field :cover_image, class: "file-input file-input-bordered w-full max-w-xs" %>
    </fieldset>
  <% if article.persisted? %>
    <div>
      <% case article.status %>
        <% when "waiting_for_review" %>
          <div class="flex justify-between">

            <%= form.submit [:admin, article], method: :patch, name: "commit_type", data: {action:"click->hello#approve"}, value: "approve", class: "btn btn-success rounded-full flex justify-between items-center text-white px-[4vw] max-px-8" do %>
              Approve
              <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="size-5">
                <path d="M15.98 1.804a1 1 0 0 0-1.96 0l-.24 1.192a1 1 0 0 1-.784.785l-1.192.238a1 1 0 0 0 0 1.962l1.192.238a1 1 0 0 1 .785.785l.238 1.192a1 1 0 0 0 1.962 0l.238-1.192a1 1 0 0 1 .785-.785l1.192-.238a1 1 0 0 0 0-1.962l-1.192-.238a1 1 0 0 1-.785-.785l-.238-1.192ZM6.949 5.684a1 1 0 0 0-1.898 0l-.683 2.051a1 1 0 0 1-.633.633l-2.051.683a1 1 0 0 0 0 1.898l2.051.684a1 1 0 0 1 .633.632l.683 2.051a1 1 0 0 0 1.898 0l.683-2.051a1 1 0 0 1 .633-.633l2.051-.683a1 1 0 0 0 0-1.898l-2.051-.683a1 1 0 0 1-.633-.633L6.95 5.684ZM13.949 13.684a1 1 0 0 0-1.898 0l-.184.551a1 1 0 0 1-.632.633l-.551.183a1 1 0 0 0 0 1.898l.551.183a1 1 0 0 1 .633.633l.183.551a1 1 0 0 0 1.898 0l.184-.551a1 1 0 0 1 .632-.633l.551-.183a1 1 0 0 0 0-1.898l-.551-.184a1 1 0 0 1-.633-.632l-.183-.551Z" />
              </svg>
            <% end %>

            <%= form.submit [:admin, article], method: :patch, name: "commit_type", data: {action:"click->hello#reject"}, value: "reject", class: "btn btn-success rounded-full flex justify-between items-center text-white px-[4vw] max-px-8" do %>
              Reject
              <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="size-5">
                <path d="M15.98 1.804a1 1 0 0 0-1.96 0l-.24 1.192a1 1 0 0 1-.784.785l-1.192.238a1 1 0 0 0 0 1.962l1.192.238a1 1 0 0 1 .785.785l.238 1.192a1 1 0 0 0 1.962 0l.238-1.192a1 1 0 0 1 .785-.785l1.192-.238a1 1 0 0 0 0-1.962l-1.192-.238a1 1 0 0 1-.785-.785l-.238-1.192ZM6.949 5.684a1 1 0 0 0-1.898 0l-.683 2.051a1 1 0 0 1-.633.633l-2.051.683a1 1 0 0 0 0 1.898l2.051.684a1 1 0 0 1 .633.632l.683 2.051a1 1 0 0 0 1.898 0l.683-2.051a1 1 0 0 1 .633-.633l2.051-.683a1 1 0 0 0 0-1.898l-2.051-.683a1 1 0 0 1-.633-.633L6.95 5.684ZM13.949 13.684a1 1 0 0 0-1.898 0l-.184.551a1 1 0 0 1-.632.633l-.551.183a1 1 0 0 0 0 1.898l.551.183a1 1 0 0 1 .633.633l.183.551a1 1 0 0 0 1.898 0l.184-.551a1 1 0 0 1 .632-.633l.551-.183a1 1 0 0 0 0-1.898l-.551-.184a1 1 0 0 1-.633-.632l-.183-.551Z" />
              </svg>
            <% end %>

          </div>
        <% when "draft" %>
          <%= button_to "Review", [ :admin, article ], params: { status: "waiting_for_review" }, method: :put, class: "btn btn-success" %>
        <% when "published" %>
          <%= button_to "Cancel", [ :admin, article ], params: { status: "draft" }, method: :put, class: "btn btn-danger" %>
      <% end %>
    </div>
  <% else %>
    <div class="flex justify-between mt-30">
      <%= link_to admin_articles_path, class: "flex items-center gap-2 hover:text-red-400" do %>
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="size-5">
          <path fill-rule="evenodd" d="M18 10a.75.75 0 0 1-.75.75H4.66l2.1 1.95a.75.75 0 1 1-1.02 1.1l-3.5-3.25a.75.75 0 0 1 0-1.1l3.5-3.25a.75.75 0 1 1 1.02 1.1l-2.1 1.95h12.59A.75.75 0 0 1 18 10Z" clip-rule="evenodd" />
        </svg>
        Cancel
      <% end %>

      <%= form.submit [:admin, article], method: :post, name: "commit_type", value: "draft", class: "btn btn-success rounded-full flex justify-between items-center text-white px-[4vw] max-px-8" do %>
        Save
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="size-5">
          <path d="M15.98 1.804a1 1 0 0 0-1.96 0l-.24 1.192a1 1 0 0 1-.784.785l-1.192.238a1 1 0 0 0 0 1.962l1.192.238a1 1 0 0 1 .785.785l.238 1.192a1 1 0 0 0 1.962 0l.238-1.192a1 1 0 0 1 .785-.785l1.192-.238a1 1 0 0 0 0-1.962l-1.192-.238a1 1 0 0 1-.785-.785l-.238-1.192ZM6.949 5.684a1 1 0 0 0-1.898 0l-.683 2.051a1 1 0 0 1-.633.633l-2.051.683a1 1 0 0 0 0 1.898l2.051.684a1 1 0 0 1 .633.632l.683 2.051a1 1 0 0 0 1.898 0l.683-2.051a1 1 0 0 1 .633-.633l2.051-.683a1 1 0 0 0 0-1.898l-2.051-.683a1 1 0 0 1-.633-.633L6.95 5.684ZM13.949 13.684a1 1 0 0 0-1.898 0l-.184.551a1 1 0 0 1-.632.633l-.551.183a1 1 0 0 0 0 1.898l.551.183a1 1 0 0 1 .633.633l.183.551a1 1 0 0 0 1.898 0l.184-.551a1 1 0 0 1 .632-.633l.551-.183a1 1 0 0 0 0-1.898l-.551-.184a1 1 0 0 1-.633-.632l-.183-.551Z" />
        </svg>
      <% end %>

      <%= form.submit [:admin, article], method: :post, name: "commit_type", value: "waiting_for_review", class: "btn btn-success rounded-full flex justify-between items-center text-white px-[4vw] max-px-8" do %>
        Submit
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="size-5">
          <path d="M15.98 1.804a1 1 0 0 0-1.96 0l-.24 1.192a1 1 0 0 1-.784.785l-1.192.238a1 1 0 0 0 0 1.962l1.192.238a1 1 0 0 1 .785.785l.238 1.192a1 1 0 0 0 1.962 0l.238-1.192a1 1 0 0 1 .785-.785l1.192-.238a1 1 0 0 0 0-1.962l-1.192-.238a1 1 0 0 1-.785-.785l-.238-1.192ZM6.949 5.684a1 1 0 0 0-1.898 0l-.683 2.051a1 1 0 0 1-.633.633l-2.051.683a1 1 0 0 0 0 1.898l2.051.684a1 1 0 0 1 .633.632l.683 2.051a1 1 0 0 0 1.898 0l.683-2.051a1 1 0 0 1 .633-.633l2.051-.683a1 1 0 0 0 0-1.898l-2.051-.683a1 1 0 0 1-.633-.633L6.95 5.684ZM13.949 13.684a1 1 0 0 0-1.898 0l-.184.551a1 1 0 0 1-.632.633l-.551.183a1 1 0 0 0 0 1.898l.551.183a1 1 0 0 1 .633.633l.183.551a1 1 0 0 0 1.898 0l.184-.551a1 1 0 0 1 .632-.633l.551-.183a1 1 0 0 0 0-1.898l-.551-.184a1 1 0 0 1-.633-.632l-.183-.551Z" />
        </svg>
      <% end %>

    </div>
  <% end %>
  </div>
<% end %>

app/views/admin/articles/edit.html.erb
<% content_for :title, "Editing article" %>

<h1>Editing article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Show this article", [ :admin, @article ] %> |
  <%= link_to "Back to articles", admin_articles_path %>
</div>

app/views/admin/articles/index.html.erb
<p style="color: green"><%= notice %></p>
<div>
  <div class="flex justify-end">
  <%= link_to "Login", admin_articles_path, class:"btn" %>
  </div>
    <div>
        <%= link_to "Create", new_admin_article_path %>
    </div>
  <div class="flex flex-col justify-center px-20">
      <div class="bg-gray-100 w-full h-100 mb-10"></div>
      <% content_for :title, "Articles", class: "text-2xl font-bold" %>

      <h1 class="text-2xl font-bold mb-6" >Articles</h1>

      <%= render "articles/articles" %>
  </div>
</div>

app/views/admin/articles/new.html.erb
<% content_for :title, "New article" %>

<div class="py-10 max-sm:px-0 px-[20vw] min-px-20">
  <div class="flex flex-col justify-center p-10 gap-30">
    <div class="flex flex-col justify-center">
    <p class="text-3xl max-sm:text-2xl font-black mx-auto">New article</p>
    <p class="flex justify-center text-lg text-gray-500 max-sm:text-md font-light text-center">Start sharing your ideas with the world</p>
    </div>
    <%= render "form", article: @article %>
  </div>
</div>

app/views/admin/articles/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @article %>

<div>
  <%= link_to "Edit this article", edit_admin_article_path(@article) %> |
  <%= link_to "Back to articles", admin_articles_path %>

  <%= button_to "Destroy this article", [ :admin, @article ], method: :delete %>
</div>